apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: logger-service
spec:
  egress:
    - hosts:
        - "logger-service/*"
        - "istio-system/*"