apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: prod
spec:
  egress:
    - hosts:
        - "prod/*"
        - "istio-system/*"
---
apiVersion: networking.istio.io/v1alpha3
kind: Sidecar
metadata:
  name: default
  namespace: prod-namespace
spec:
  egress:
    - hosts:
        - "prod-namespace/*"
        - "istio-system/*"
